_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 192
  BASE_LR: 0.12
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
INPUT: 
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024,)
  MIN_SIZE_TEST: 608
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val', 'Hypersim_train', 'Hypersim_val', 'ARKitScenes_train', 'ARKitScenes_val', 'Objectron_train', 'Objectron_val', 'nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val')
  TEST: ('SUNRGBD_test', 'Hypersim_test', 'ARKitScenes_test', 'Objectron_test', 'KITTI_test', 'nuScenes_test') 
  CATEGORY_NAMES: ('chair', 'table', 'cabinet', 'car', 'lamp', 'books', 'sofa', 'pedestrian', 'picture', 'window', 'pillow', 'truck', 'door', 'blinds', 'sink', 'shelves', 'television', 'shoes', 'cup', 'bottle', 'bookcase', 'laptop', 'desk', 'cereal box', 'floor mat', 'traffic cone', 'mirror', 'barrier', 'counter', 'camera', 'bicycle', 'toilet', 'bus', 'bed', 'refrigerator', 'trailer', 'box', 'oven', 'clothes', 'van', 'towel', 'motorcycle', 'night stand', 'stove', 'machine', 'stationery', 'bathtub', 'cyclist', 'curtain', 'bin')
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]  # changed to rgb order
  BACKBONE:
    FREEZE_AT: 0 
    NAME: 'build_clip_backbone'
  CLIP:
    ARCH: 'ViT-B-16'
    CHECKPOINT: 'openai'
    OUTPUT: 'dense'
    LAYER: -1
    RETURN_MULTILAYER: False
  FPN:
    IN_FEATURE: 'last_feat'
    NORM: 'LN'
    SQUARE_PAD: 1024
  ANCHOR_GENERATOR:
    SIZES: [[64], [128], [256], [512]] 
  RPN:
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
  ROI_HEADS:
    NUM_CLASSES: 50
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']